# Development docker-compose with hot reload

services:
  mongodb:
    image: mongo:7.0
    container_name: agri-mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - agri-network-dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agri-backend-dev
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=agri_dashboard
      - DEBUG=True
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - agri-network-dev
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:18-alpine
    container_name: agri-frontend-dev
    working_dir: /app
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - agri-network-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"

networks:
  agri-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev:
    driver: local
